package rule
import java.util.Map

rule "유선 상품 추천"
    no-loop true
    lock-on-active true
    salience 3
    when
        $map : Map(
		this["CUST_CTG_TYPE_NM"] == "개인" &&
		this["CUST_AGE"] > 24 &&
		this["INDV_INFO_COLEC_USE_AGREE_YN"] == "Y" &&
		this["SMPH_USE_YN"] == "N" )
    then
        $map.put("RuleName_유선 상품 추천", 3.1);
end

rule "미납 고객 대상 추출"
    no-loop true
    lock-on-active true
    salience 2
    when
        $map : Map(
		this["CUST_AGE"] > 24 &&
		this["CUST_CTG_TYPE_NM"] == "개인" &&
		this["NPAY_YN"] == "Y" )
    then
        $map.put("RuleName_미납 고객 대상 추출", 2.2);
end

rule "무선 상품 5G 추천"
    no-loop true
    lock-on-active true
    salience 1
    when
        $map : Map(
		this["CUST_CTG_TYPE_NM"] == "개인" &&
		this["SMPH_USE_YN"] == "Y" &&
		this["CUST_AGE"] > 24 &&
		this["INDV_INFO_COLEC_USE_AGREE_YN"] == "Y" &&
		this["CUST_CLAS_NM"] == "VIP" )
    then
        $map.put("RuleName_무선 상품 5G 추천", 1.3);
end