package rule
import java.util.Map

rule "고객룰"
    no-loop true
    lock-on-active true
    salience 3
    when
        $map : Map(
		this["SEX_TYPE_NM"] == "여자" &&
		this["CUST_AGE"] == 24 )
    then
        $map.put("RuleName_고객룰", 3.1);
end

rule "등급룰"
    no-loop true
    lock-on-active true
    salience 3
    when
        $map : Map(
		this["CUST_CLAS_NM"] == "Gold" )
    then
        $map.put("RuleName_등급룰", 3.2);
end

rule "미납룰"
    no-loop true
    lock-on-active true
    salience 1
    when
        $map : Map(
		this["NPAY_YN"] == "N" )
    then
        $map.put("RuleName_미납룰", 1.3);
end

rule "고객분류룰"
    no-loop true
    lock-on-active true
    salience 1
    when
        $map : Map(
		this["CUST_CTG_TYPE_NM"] == "개인" )
    then
        $map.put("RuleName_고객분류룰", 1.4);
end

rule "개인정보룰"
    no-loop true
    lock-on-active true
    salience 2
    when
        $map : Map(
		this["INDV_INFO_COLEC_USE_AGREE_YN"] == "Y" )
    then
        $map.put("RuleName_개인정보룰", 2.5);
end