package rules

import egovframework.example.sample.web.Order
import java.util.Map
/*
rule "zero"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Map(this["amout"] <= 100)
    then
        $s.put("score",0);
        update($s);
        System.out.println( $s.get("amout") );
end

rule "add100"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Map(this["amout"] > 100 && this["amout"] <= 500)
    then
        $s.put("score",400);
        update($s);
end

rule "add500"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Map(this["amout"] > 500 && this["amout"] <= 1000)
    then
        $s.put("score",500);
        update($s);
end

rule "add1000"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Map(this["amout"] > 1000)
    then
        $s.put("score",1000);
        update($s);
end


rule "zero"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Order(amout <= 100)
    then
        $s.setScore(0);
        update($s);
        System.out.println( $s.getAmout() );
end

rule "add100"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Order(amout > 100 && amout <= 500)
    then
        $s.setScore(400);
        update($s);
end

rule "add500"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Order(amout > 500 && amout <= 1000)
    then
        $s.setScore(500);
        update($s);
end

rule "add1000"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Order(amout > 1000)
    then
        $s.setScore(1000);
        update($s);
end
*/